#!/bin/sh

case "$1" in
  configure)
  	if ! [ `egrep -i "^groupname" /etc/group` ]; then
  	  addgroup --system watchtower 
  	if ! [ `getent passwd watchtower-monitoring` ]; then
      adduser --system --group -G watchtower watchtower-monitoring
    fi
    
    if ! [ -d "/var/log/watchtower/" ]; then
      mkdir -p /var/log/watchtower/
      chown watchtower-monitoring:watchtower /var/log/watchtower/
    fi
  ;;
esac

exit 0